POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "andy1",
    "password": "andyhth"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "andy1",
    "password": "andyhth"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMTRmZjUyYjc5NjA5MDg0M2ExODYiLCJpYXQiOjE2MTc4OTkzNDl9.91KcT8QaVxstQzff7CM-E1A97lLCVPTphdb4z54us8A

{
    "title": "React",
    "description": "pratice react",
    "url": "youtube.com",
    "status": "LEARNING"
}
###
GET  http://localhost:5000/api/posts
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMTRmZjUyYjc5NjA5MDg0M2ExODYiLCJpYXQiOjE2MTc4OTkzNDl9.91KcT8QaVxstQzff7CM-E1A97lLCVPTphdb4z54us8A
###
PUT  http://localhost:5000/api/posts/606f2f859c73333ae0b40fda
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDZmMTRmZjUyYjc5NjA5MDg0M2ExODYiLCJpYXQiOjE2MTc4OTkzNDl9.91KcT8QaVxstQzff7CM-E1A97lLCVPTphdb4z54us8A

{
    "title": "react",
    "description": "VUEEEE",
    "url": "https://vuejs.org",
    "status": "LEARNING"
}

